services:
  - type: web
    name: spring-boot-demo
    env: java
    buildCommand: ./gradlew build
    startCommand: java -jar build/libs/app.jar
    envVars:
      - key: PORT
        value: 8080
      - key: JAVA_VERSION
        value: 17 